#pragma once

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

// mouse
#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MK_C_OFFSET_UNMOD 14
#define MK_C_OFFSET_0 2

// RGB
#define RGB_MATRIX_DEFAULT_HUE 191 // purple
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define RGB_MATRIX_TYPING_HEATMAP_SPREAD 25

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
