#pragma once

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000

// mouse
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_MOVE_DELTA 6

// RGB
#define RGB_MATRIX_DEFAULT_HUE 191 // purple
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define RGB_MATRIX_TYPING_HEATMAP_SPREAD 25

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
